export const statesWithCities = [
  {
    state: "Addis Ababa",
    cities: ["Addis Ababa"],
  },
  {
    state: "Afar",
    cities: [
      "Asaita",
      "Dubti",
      "Awash",
      "Logiya",
      "Abala",
      "Chifra",
      "Mile",
      "Semera",
      "Gewane",
      "Erebti",
      "Dalol",
    ],
  },
  {
    state: "Amhara",
    cities: [
      "Bahir Dar",
      "Gondar",
      "Dessie",
      "Debre Birhan",
      "Debre Markos",
      "Debre Tabor",
      "Kombolcha",
      "Woldia",
      "Adet",
      "Kemise",
      "Finote Selam",
    ],
  },
  {
    state: "Benishangul-Gumuz",
    cities: [
      "Asosa",
      "Bambasi",
      "Dibate",
      "Menkwer",
      "Sherkole",
      "Kumruk",
      "Tulu Bolo",
      "Ardi",
      "Agnuak",
      "Metekel",
    ],
  },
  {
    state: "Central Ethiopia",
    cities: [
      "Hosaena",
      "Welkite",
      "Butajira",
      "Worabe",
      "Durame",
      "Halaba Kulito",
      "Saja",
      "Wosherbe",
      "Koshe",
      "Mudula",
      "Emdibir",
    ],
  },
  {
    state: "Dire Dawa",
    cities: ["Dire Dawa"],
  },
  {
    state: "Gambela",
    cities: ["Gambela", "Itang", "Gog", "Jor", "Pochalla", "Akobo", "Wennag"],
  },
  {
    state: "Harari",
    cities: ["Harar", "Gelemso", "Erer", "Kombolcha"],
  },
  {
    state: "Oromia",
    cities: [
      "Adama",
      "Bishoftu",
      "Jimma",
      "Nekemte",
      "Ambo",
      "Shashamane",
      "Bule Hora",
      "Dembi Dolo",
      "Gimbi",
      "Fiche",
      "Asella",
    ],
  },
  {
    state: "Sidama",
    cities: [
      "Hawassa",
      "Aleta Wendo",
      "Yirgalem",
      "Boricha",
      "Bensa",
      "Hula",
      "Loka Abaya",
      "Aleta Chuko",
      "Boditi",
      "Wendo Genet",
      "Aroresa",
    ],
  },
  {
    state: "Somali",
    cities: [
      "Jijiga",
      "Gode",
      "Degehabur",
      "Kebri Dehar",
      "Dolo",
      "Togo",
      "Hartisho",
      "Shilabo",
      "Filtu",
      "Charati",
      "Danot",
    ],
  },
  {
    state: "South Ethiopia",
    cities: [
      "Arba Minch",
      "Wolaita Sodo",
      "Dilla",
      "Jinka",
      "Areka",
      "Boditi",
      "Gununo",
      "Felege Neway",
      "Tercha",
      "Basketo",
      "Gidole",
    ],
  },
  {
    state: "South West Ethiopia",
    cities: [
      "Bonga",
      "Tepi",
      "Mizan Teferi",
      "Komticha",
      "Wacha",
      "Waka",
      "Tarcha",
      "Majiseng",
      "Gecha",
      "Bitta",
      "Sheko",
    ],
  },
  {
    state: "Tigray",
    cities: [
      "Mekelle",
      "Adigrat",
      "Axum",
      "Shire",
      "Adwa",
      "Alamata",
      "Wukro",
      "Maychew",
      "Humera",
      "Abi Adi",
      "Korem",
    ],
  },
];
